# Generated by Django 2.1.4 on 2018-12-25 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editors', '0005_editors_registered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('file_1', models.FileField(blank=True, upload_to='files/%Y/%m/%d')),
                ('file_2', models.FileField(blank=True, upload_to='files/%Y/%m/%d')),
                ('file_3', models.FileField(blank=True, upload_to='files/%Y/%m/%d')),
                ('file_4', models.FileField(blank=True, upload_to='files/%Y/%m/%d')),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_published', models.BooleanField(default=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='editors.Editors')),
            ],
        ),
    ]
