# Generated by Django 2.1.4 on 2018-12-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editors',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
