# Generated by Django 2.1.4 on 2018-12-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editors', '0003_auto_20181225_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='editors',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
